---
title: 갑자기 마주한 ChunkLoadError 해결하기
date: "2024-11-05"
tags: [errorlog]
description:  어느 날 갑자기 에러 화면과 함께 console창에 ChunkLoadError가 찍혔다.
thumbnail: "./images/error-log-thumbnail.png" 
---


 <img
    src="https://blog.kakaocdn.net/dn/QVBZA/btsKyesaiap/J1gpij3knSAts2W7CCKkt0/img.png"
    className="m-auto"
  />


## 문제파악

어느 날부터 간헐적으로 ChunkLoadError가 발생했다.

보통 이러한 이슈는 배포 후 chunk 파일의 해쉬가 새롭게 바뀌면서 이전 파일을 보고있던 사용자가 페이지를 이동할 때 이전 chunk파일을 찾기 때문에 발생하는 이슈이다. 하지만 나의 경우 배포여부와 상관없이 chunk를 로드하지 못했다는 에러를 뿜어냈다.

source탭에서 가져온 파일을 살펴보니 `812.b596d57c.chunk.js` 파일은 최신배포 버전에 속한 파일이 맞으며, 실제 존재한다.

다만 해당 이슈가 발생했을때는 원인은 모르겠지만 해당 chunk파일을 비롯한 몇몇 chunk파일을 가져오지 않고있었다.

동일한 프로젝트를 배포한 다른 환경에서는 해당 현상이 발생하지 않는 것을 확인했다. 이를 통해 코드나 서버 설정보다는 내가 컨트롤할 수 없는 네트워크나 특정 환경적인 문제일 것이라 판단했다.

<br/>
<br/>

## 해결?

하지만 그렇다고 이슈를 방치할 수는 없었기 때문에, 코드스플리팅 부분에 방어 코드를 추가했다. chunk파일을 로드하지 못하는 상황이 발생할 경우, 이를 재시도하도록 설정하여 에러 상황에서도 chunk 파일을 정상적으로 로드할 수 있도록 개선했다.

```

const retry = (
  callback: () => LazyImport,
  retries = 5,
  interval = 1000
): LazyImportResult => {
  return new Promise((resolve, reject) => {
    callback()
      .then(resolve)
      .catch((error) => {
        if (retries <= 1) {
          reject(error);
          return;
        }
        setTimeout(() => {
          retry(callback, retries - 1, interval).then(resolve, reject);
        }, interval);
      });
  });
};

const lazyRetry = (importFunc: () => LazyImport) =>
  lazy(() => retry(importFunc));

```



```

const Main = withSuspense(lazyRetry(() => import('@/components/pages/Main')));
```
이런 식으로 사용해주면 된다.






